package com.example.ui.screens

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.LocationOn
import androidx.compose.material.icons.filled.Map
import androidx.compose.material.icons.filled.Directions
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.example.gajananmandir.R

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun TempleLocationScreen() {
    Scaffold(
            topBar = {
                        TopAppBar(
                                        title = { Text("Temple Location") }
                                                    )
                                                            }
                                                                ) { padding ->
                                                                        Column(
                                                                                    modifier = Modifier
                                                                                                    .fillMaxSize()
                                                                                                                    .padding(padding)
                                                                                                                                    .padding(16.dp),
                                                                                                                                                horizontalAlignment = Alignment.CenterHorizontally,
                                                                                                                                                            verticalArrangement = Arrangement.spacedBy(16.dp)
                                                                                                                                                                    ) {
                                                                                                                                                                                Card(
                                                                                                                                                                                                modifier = Modifier.fillMaxWidth(),
                                                                                                                                                                                                                shape = RoundedCornerShape(16.dp),
                                                                                                                                                                                                                                elevation = CardDefaults.cardElevation(8.dp)
                                                                                                                                                                                                                                            ) {
                                                                                                                                                                                                                                                            Column(
                                                                                                                                                                                                                                                                                modifier = Modifier.padding(16.dp),
                                                                                                                                                                                                                                                                                                    verticalArrangement = Arrangement.spacedBy(12.dp)
                                                                                                                                                                                                                                                                                                                    ) {
                                                                                                                                                                                                                                                                                                                                        Row(verticalAlignment = Alignment.CenterVertically) {
                                                                                                                                                                                                                                                                                                                                                                Icon(Icons.Filled.LocationOn, contentDescription = null)
                                                                                                                                                                                                                                                                                                                                                                                        Spacer(modifier = Modifier.width(8.dp))
                                                                                                                                                                                                                                                                                                                                                                                                                Text("Shri Gajanan Maharaj Mandir, Shegaon", style = MaterialTheme.typography.titleMedium)
                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                        Row(verticalAlignment = Alignment.CenterVertically) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Icon(Icons.Filled.Map, contentDescription = null)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Spacer(modifier = Modifier.width(8.dp))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Text("Maharashtra, India - 444203")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Row(verticalAlignment = Alignment.CenterVertically) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Icon(Icons.Filled.Directions, contentDescription = null)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Spacer(modifier = Modifier.width(8.dp))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Text("Open in Maps")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Card(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        modifier = Modifier.fillMaxWidth().height(200.dp),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        shape = RoundedCornerShape(16.dp)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Text("Map View Here")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }